LITE-19949: Added new SLA report
cloudblue/connect-reports pull request #16
Opened 2021-08-27 11:35 UTC by gab832

New SLA report added also with tests.

2021-08-30 08:22 UTC, gab832 commented on tests/test_sla.py
> +        print(f'[{index}] Comparing {element} VS {expected[index]}')
Yes, sure, thanks!

2021-09-13 13:58 UTC, marcserrat approved these changes

2021-09-13 14:45 UTC, ffaraoneim requested changes

2021-09-13 14:45 UTC, ffaraoneim commented on reports/sla/entrypoint.py
> +    return (datetime.datetime.now() - convert_to_datetime(data['created'])).days
Probably we should ensure that all datetime calculations are made in the same timezone. 

datetime.datetime.now() returns the local time but if I'm not wrong data['created'] is UTC.
Could you please check ?

2021-09-13 15:59 UTC, ffaraoneim approved these changes

2021-09-13 16:55 UTC, merged